{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-unified-platform/2.0/kotlin-unified-platform-2.0.module",
    "group": "net.notjustanna",
    "module": "kotlin-unified-platform",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-unified-platform-tvosSimulatorArm64Main-2.0.klib",
          "url": "kotlin-unified-platform-tvossimulatorarm64-2.0.klib",
          "size": 27457,
          "sha512": "3c732bb33da7343e2713c7305f17e67bf492a35d63520378b7d8e773e4cca445eb402797b908d351ee3b655a4052bbc79e85b9f502e2d094a06fbd1aa021447e",
          "sha256": "aa20cdc9796a4b86210efbf172f399bd64269f7fbd56499fc3ec1d7d41d47884",
          "sha1": "742a7dace949ae7fa3e3b891a1e3e8b4f20e8840",
          "md5": "892b03864000270d88d89add80dfdfee"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-unified-platform-tvossimulatorarm64-2.0-sources.jar",
          "url": "kotlin-unified-platform-tvossimulatorarm64-2.0-sources.jar",
          "size": 5894,
          "sha512": "dc837c699729c0c010af40c0f83d9ab68a432ba6d6090b6dad5251f87e959f5f0f3abbf51daf9381f09dbae9c9ae588901a94312da6189ec147a57e9972d6e3a",
          "sha256": "a0cd8d290c146a58c317c815689c5a6e8ca195a83620de4a7a4c8bf5cb058819",
          "sha1": "2870986fa3c746d4b2b1d20523c066af0856bf15",
          "md5": "fecc4ff3e72a5641546fe2fb98e778f9"
        }
      ]
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-unified-platform-tvossimulatorarm64-2.0-metadata.jar",
          "url": "kotlin-unified-platform-tvossimulatorarm64-2.0-metadata.jar",
          "size": 261,
          "sha512": "2206c4e19266ed2ee823a3af6c2de0c32bbf798ac5ec63be701ab77e32849e487dde73fc48cd3bb6f665a4cec4cbb00018ea199d79453be41ed3e5f1d78c7b1c",
          "sha256": "c231cf34c6ee89ac15c8a1c4d1ba8e416475a68f2f86df9e78cb197202d6755e",
          "sha1": "02513aaa75f32e1c1e9d63451319880a9b049c17",
          "md5": "c407fff77e268f17c97f8e278244e3ea"
        }
      ]
    }
  ]
}
