{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-unified-platform/2.0/kotlin-unified-platform-2.0.module",
    "group": "net.notjustanna",
    "module": "kotlin-unified-platform",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-unified-platform-watchosDeviceArm64Main-2.0.klib",
          "url": "kotlin-unified-platform-watchosdevicearm64-2.0.klib",
          "size": 27459,
          "sha512": "ed2e8c5d354e9432265b3e7a430068f158ccbc97393b536685f06bd5f0f1f5479d8c825076f70553697c1d837c6c5e88453cde199d5a4a04378d2c40ea37ca4c",
          "sha256": "5a3de96a5c01155ad559796ed35593920f1c070321c650b1757eedc8035a2f6a",
          "sha1": "f0a7f9f0669713222f093b09985a923b5efd8657",
          "md5": "db9cc41ec0281ad67c16a20f150546fc"
        }
      ]
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-unified-platform-watchosdevicearm64-2.0-sources.jar",
          "url": "kotlin-unified-platform-watchosdevicearm64-2.0-sources.jar",
          "size": 5894,
          "sha512": "dc837c699729c0c010af40c0f83d9ab68a432ba6d6090b6dad5251f87e959f5f0f3abbf51daf9381f09dbae9c9ae588901a94312da6189ec147a57e9972d6e3a",
          "sha256": "a0cd8d290c146a58c317c815689c5a6e8ca195a83620de4a7a4c8bf5cb058819",
          "sha1": "2870986fa3c746d4b2b1d20523c066af0856bf15",
          "md5": "fecc4ff3e72a5641546fe2fb98e778f9"
        }
      ]
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-unified-platform-watchosdevicearm64-2.0-metadata.jar",
          "url": "kotlin-unified-platform-watchosdevicearm64-2.0-metadata.jar",
          "size": 261,
          "sha512": "4827af37a26ce62a95a4b3424a816317e6db75b62ab0d0747729024a84fb84816a3f5ea53123bc908fef447870b9eef63afba418dc1e2f4c1f0fd9a87187a699",
          "sha256": "148e8e64e7c2b71494ba71f7f606fbeed670d48f9cc01daff583a598bbb5b56e",
          "sha1": "dbc4194a6980bca7cc3ca66db815073dacdca466",
          "md5": "7b9a2912f972ff10a8acfa519d085987"
        }
      ]
    }
  ]
}
