{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-unified-platform/2.0/kotlin-unified-platform-2.0.module",
    "group": "net.notjustanna",
    "module": "kotlin-unified-platform",
    "version": "2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-unified-platform-watchosX64Main-2.0.klib",
          "url": "kotlin-unified-platform-watchosx64-2.0.klib",
          "size": 27401,
          "sha512": "beb1fba653136c0af38d7eaa85947c2ec5cf93f641ef085acd776bd281a18327c745491f26682c6a7704f3e088802825d4f69dd1b1c5ec897d016de366aa9c6d",
          "sha256": "e7c071dab48207ef8a3fb73a4ce51c036bdd939207651847099981d80f39278d",
          "sha1": "640582ecd60f5c57fa9c8b159a85b6976f5669ab",
          "md5": "1e412054e0ca49d94e95b43e68418fb6"
        }
      ]
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "files": [
        {
          "name": "kotlin-unified-platform-watchosx64-2.0-sources.jar",
          "url": "kotlin-unified-platform-watchosx64-2.0-sources.jar",
          "size": 5894,
          "sha512": "dc837c699729c0c010af40c0f83d9ab68a432ba6d6090b6dad5251f87e959f5f0f3abbf51daf9381f09dbae9c9ae588901a94312da6189ec147a57e9972d6e3a",
          "sha256": "a0cd8d290c146a58c317c815689c5a6e8ca195a83620de4a7a4c8bf5cb058819",
          "sha1": "2870986fa3c746d4b2b1d20523c066af0856bf15",
          "md5": "fecc4ff3e72a5641546fe2fb98e778f9"
        }
      ]
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-unified-platform-watchosx64-2.0-metadata.jar",
          "url": "kotlin-unified-platform-watchosx64-2.0-metadata.jar",
          "size": 261,
          "sha512": "4827af37a26ce62a95a4b3424a816317e6db75b62ab0d0747729024a84fb84816a3f5ea53123bc908fef447870b9eef63afba418dc1e2f4c1f0fd9a87187a699",
          "sha256": "148e8e64e7c2b71494ba71f7f606fbeed670d48f9cc01daff583a598bbb5b56e",
          "sha1": "dbc4194a6980bca7cc3ca66db815073dacdca466",
          "md5": "7b9a2912f972ff10a8acfa519d085987"
        }
      ]
    }
  ]
}
